ALTER SESSION SET "_oracle_script" = TRUE; 

--TASK 1
CREATE TABLESPACE "TS_KNS"
DATAFILE 'ts_kns.dbf'
SIZE 7M 
AUTOEXTEND ON NEXT 5M 
MAXSIZE 20M;

--
CREATE TEMPORARY TABLESPACE "TS_KNS_TEMP"
TEMPFILE 'ts_kns_temp.dbf'
SIZE 5M 
AUTOEXTEND ON NEXT 3M 
MAXSIZE 30M;

drop tablespace TS_KNS_TEMP;
--
select tablespace_name from dba_tablespaces;
select file_name, tablespace_name FROM DBA_DATA_FILES;
select file_name, tablespace_name FROM DBA_TEMP_FILES;
--
CREATE ROLE RL_KNSCORE;
GRANT CONNECT,
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    DROP ANY TABLE,
    DROP ANY VIEW,
    DROP ANY PROCEDURE TO RL_KNSCORE;
    
--
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_KNSCORE';

SELECT * FROM USER_SYS_PRIVS; 
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

--

CREATE PROFILE PF_KNSCORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_KNSCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

--
CREATE USER KNSCORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_KNS QUOTA UNLIMITED ON TS_KNS
TEMPORARY TABLESPACE TS_KNS_TEMP
PROFILE PF_KNSCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_KNSCORE TO KNSCORE;

drop user KNSCORE;

CREATE TABLESPACE KNS_QDATA OFFLINE
DATAFILE 'kns_qdata.txt'
SIZE 10M REUSE
AUTOEXTEND ON NEXT 5M
MAXSIZE 20M;

ALTER TABLESPACE KNS_QDATA ONLINE;

ALTER USER KNSCORE QUOTA 2M on KNS_QDATA;

CREATE TABLE t (c NUMBER) TABLESPACE KNS_QDATA;
INSERT INTO t(c) VALUES(3);
INSERT INTO t(c) VALUES(1);
INSERT INTO t(c) VALUES(2);
COMMIT;
SELECT * FROM KNSCORE.t;
